spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?useUnicode=true&characterEncoding=utf-8
    username: root
    password: sifu
  thymeleaf:
    cache: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
# 添加如下是拦截 swagger-ui.html 请求需要密码登陆
security:
  basic:
    path: /swagger-ui.html
    enabled: true
  user:
    name: root
    password: 123456
